export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export type GET_USERS_REQUEST = typeof GET_USERS_REQUEST;

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export type GET_USERS_SUCCESS = typeof GET_USERS_SUCCESS;

export const GET_USERS_FAIL = "GET_USERS_FAIL";
export type GET_USERS_FAIL = typeof GET_USERS_FAIL;

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export type GET_USER_REQUEST = typeof GET_USER_REQUEST;

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export type GET_USER_SUCCESS = typeof GET_USER_SUCCESS;

export const GET_USER_FAIL = "GET_USER_FAIL";
export type GET_USER_FAIL = typeof GET_USER_FAIL;

export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST";
export type ADD_USERS_REQUEST = typeof ADD_USERS_REQUEST;

export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export type ADD_USERS_SUCCESS = typeof ADD_USERS_SUCCESS;

export const ADD_USERS_FAIL = "ADD_USERS_FAIL";
export type ADD_USERS_FAIL = typeof ADD_USERS_FAIL;

export const UPDATE_USERS_REQUEST = "UPDATE_USERS_REQUEST";
export type UPDATE_USERS_REQUEST = typeof UPDATE_USERS_REQUEST;

export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
export type UPDATE_USERS_SUCCESS = typeof UPDATE_USERS_SUCCESS;

export const UPDATE_USERS_FAIL = "UPDATE_USERS_FAIL";
export type UPDATE_USERS_FAIL = typeof UPDATE_USERS_FAIL;

export const DELETE_USERS_REQUEST = "DELETE_USERS_REQUEST";
export type DELETE_USERS_REQUEST = typeof DELETE_USERS_REQUEST;

export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export type DELETE_USERS_SUCCESS = typeof DELETE_USERS_SUCCESS;

export const DELETE_USERS_FAIL = "DELETE_USERS_FAIL";
export type DELETE_USERS_FAIL = typeof DELETE_USERS_FAIL;

export const SHOW_COMMENTS = "SHOW_COMMENTS";
export type SHOW_COMMENTS = typeof SHOW_COMMENTS;
