export const GET_ROLES_REQUEST = "GET_ROLES_REQUEST";
export type GET_ROLES_REQUEST = typeof GET_ROLES_REQUEST;

export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export type GET_ROLES_SUCCESS = typeof GET_ROLES_SUCCESS;

export const GET_ROLES_FAIL = "GET_ROLES_FAIL";
export type GET_ROLES_FAIL = typeof GET_ROLES_FAIL;

export const ADD_ROLES_REQUEST = "ADD_ROLES_REQUEST";
export type ADD_ROLES_REQUEST = typeof ADD_ROLES_REQUEST;

export const ADD_ROLES_SUCCESS = "ADD_ROLES_SUCCESS";
export type ADD_ROLES_SUCCESS = typeof ADD_ROLES_SUCCESS;

export const ADD_ROLES_FAIL = "ADD_ROLES_FAIL";
export type ADD_ROLES_FAIL = typeof ADD_ROLES_FAIL;

export const DELETE_ROLES_REQUEST = "DELETE_ROLES_REQUEST";
export type DELETE_ROLES_REQUEST = typeof DELETE_ROLES_REQUEST;

export const DELETE_ROLES_SUCCESS = "DELETE_ROLES_SUCCESS";
export type DELETE_ROLES_SUCCESS = typeof DELETE_ROLES_SUCCESS;

export const DELETE_ROLES_FAIL = "DELETE_ROLES_FAIL";
export type DELETE_ROLES_FAIL = typeof DELETE_ROLES_FAIL;

export const SHOW_COMMENTS = "SHOW_COMMENTS";
export type SHOW_COMMENTS = typeof SHOW_COMMENTS;
