export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export type GET_COMMENTS_REQUEST = typeof GET_COMMENTS_REQUEST;

export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export type GET_COMMENTS_SUCCESS = typeof GET_COMMENTS_SUCCESS;

export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
export type GET_COMMENTS_FAIL = typeof GET_COMMENTS_FAIL;

export const CREATE_COMMENTS_REQUEST = "CREATE_COMMENTS_REQUEST";
export type CREATE_COMMENTS_REQUEST = typeof CREATE_COMMENTS_REQUEST;

export const CREATE_COMMENTS_SUCCESS = "CREATE_COMMENTS_SUCCESS";
export type CREATE_COMMENTS_SUCCESS = typeof CREATE_COMMENTS_SUCCESS;

export const CREATE_COMMENTS_FAIL = "CREATE_COMMENTS_FAIL";
export type CREATE_COMMENTS_FAIL = typeof CREATE_COMMENTS_FAIL;
