export const GET_RECORDS_REQUEST = "GET_RECORDS_REQUEST";
export type GET_RECORDS_REQUEST = typeof GET_RECORDS_REQUEST;

export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export type GET_RECORDS_SUCCESS = typeof GET_RECORDS_SUCCESS;

export const GET_RECORDS_FAIL = "GET_RECORDS_FAIL";
export type GET_RECORDS_FAIL = typeof GET_RECORDS_FAIL;

export const GET_RECORD_REQUEST = "GET_RECORD_REQUEST";
export type GET_RECORD_REQUEST = typeof GET_RECORD_REQUEST;

export const GET_RECORD_SUCCESS = "GET_RECORD_SUCCESS";
export type GET_RECORD_SUCCESS = typeof GET_RECORD_SUCCESS;

export const GET_RECORD_FAIL = "GET_RECORD_FAIL";
export type GET_RECORD_FAIL = typeof GET_RECORD_FAIL;

export const ADD_RECORDS_REQUEST = "ADD_RECORDS_REQUEST";
export type ADD_RECORDS_REQUEST = typeof ADD_RECORDS_REQUEST;

export const ADD_RECORDS_SUCCESS = "ADD_RECORDS_SUCCESS";
export type ADD_RECORDS_SUCCESS = typeof ADD_RECORDS_SUCCESS;

export const ADD_RECORDS_FAIL = "ADD_RECORDS_FAIL";
export type ADD_RECORDS_FAIL = typeof ADD_RECORDS_FAIL;

export const UPDATE_RECORDS_REQUEST = "UPDATE_RECORDS_REQUEST";
export type UPDATE_RECORDS_REQUEST = typeof UPDATE_RECORDS_REQUEST;

export const UPDATE_RECORDS_SUCCESS = "UPDATE_RECORDS_SUCCESS";
export type UPDATE_RECORDS_SUCCESS = typeof UPDATE_RECORDS_SUCCESS;

export const UPDATE_RECORDS_FAIL = "UPDATE_RECORDS_FAIL";
export type UPDATE_RECORDS_FAIL = typeof UPDATE_RECORDS_FAIL;

export const DELETE_RECORDS_REQUEST = "DELETE_RECORDS_REQUEST";
export type DELETE_RECORDS_REQUEST = typeof DELETE_RECORDS_REQUEST;

export const DELETE_RECORDS_SUCCESS = "DELETE_RECORDS_SUCCESS";
export type DELETE_RECORDS_SUCCESS = typeof DELETE_RECORDS_SUCCESS;

export const DELETE_RECORDS_FAIL = "DELETE_RECORDS_FAIL";
export type DELETE_RECORDS_FAIL = typeof DELETE_RECORDS_FAIL;

export const SHOW_COMMENTS = "SHOW_COMMENTS";
export type SHOW_COMMENTS = typeof SHOW_COMMENTS;
