export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export type GET_WEATHER_REQUEST = typeof GET_WEATHER_REQUEST;

export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export type GET_WEATHER_SUCCESS = typeof GET_WEATHER_SUCCESS;

export const GET_WEATHER_FAIL = "GET_WEATHER_FAIL";
export type GET_WEATHER_FAIL = typeof GET_WEATHER_FAIL;
