export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export type GET_COMMENTS_REQUEST = typeof GET_COMMENTS_REQUEST;

export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export type GET_COMMENTS_SUCCESS = typeof GET_COMMENTS_SUCCESS;

export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
export type GET_COMMENTS_FAIL = typeof GET_COMMENTS_FAIL;
