export const GET_RECORDS_REQUEST = "GET_RECORDS_REQUEST";
export type GET_RECORDS_REQUEST = typeof GET_RECORDS_REQUEST;

export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export type GET_RECORDS_SUCCESS = typeof GET_RECORDS_SUCCESS;

export const GET_RECORDS_FAIL = "GET_RECORDS_FAIL";
export type GET_RECORDS_FAIL = typeof GET_RECORDS_FAIL;

export const ADD_RECORDS_REQUEST = "ADD_RECORDS_REQUEST";
export type ADD_RECORDS_REQUEST = typeof ADD_RECORDS_REQUEST;

export const ADD_RECORDS_SUCCESS = "ADD_RECORDS_SUCCESS";
export type ADD_RECORDS_SUCCESS = typeof ADD_RECORDS_SUCCESS;

export const ADD_RECORDS_FAIL = "ADD_RECORDS_FAIL";
export type ADD_RECORDS_FAIL = typeof ADD_RECORDS_FAIL;

export const SHOW_COMMENTS = "SHOW_COMMENTS";
export type SHOW_COMMENTS = typeof SHOW_COMMENTS;
